import type { CabinetConfig, FurnitureType } from './types';
import {
  DEFAULT_CONFIG,
  BOOKSHELF_DEFAULTS,
  CABINET_DEFAULTS,
  DESK_DEFAULTS,
  WARDROBE_DEFAULTS,
  PANEL_DEFAULTS,
} from './materials';

export interface CabinetTemplate {
  id: string;
  name: { en: string; he: string };
  description: { en: string; he: string };
  icon: string; // icon component name from Icons.tsx
  config: CabinetConfig;
}

function tpl(
  id: string,
  nameEn: string,
  nameHe: string,
  descEn: string,
  descHe: string,
  icon: string,
  overrides: Partial<CabinetConfig>,
): CabinetTemplate {
  return {
    id,
    name: { en: nameEn, he: nameHe },
    description: { en: descEn, he: descHe },
    icon,
    config: { ...DEFAULT_CONFIG, ...overrides },
  };
}

export const TEMPLATES: CabinetTemplate[] = [
  tpl(
    'kitchen-base',
    'Kitchen Base Unit',
    'ארון בסיס מטבח',
    '600×850×560 mm standard base unit with 2 doors and toe kick',
    'ארון בסיס תקני 600×850×560 מ"מ, 2 דלתות, בסיס',
    'IconKitchen',
    {
      furnitureType: 'cabinet',
      width: 600,
      height: 850,
      depth: 560,
      shelfCount: 1,
      doorCount: 2,
      doorStyle: 'flat',
      handleStyle: 'bar',
      kickHeight: 100,
      carcassMaterial: 'melamine-16',
      backPanelMaterial: 'hdf-3',
      edgeBanding: 'all-visible',
    },
  ),
  tpl(
    'kitchen-wall',
    'Kitchen Wall Unit',
    'ארון תלייה מטבח',
    '600×720×320 mm wall-mounted cabinet with 2 doors',
    'ארון תלייה מטבח 600×720×320 מ"מ, 2 דלתות',
    'IconWallUnit',
    {
      furnitureType: 'cabinet',
      width: 600,
      height: 720,
      depth: 320,
      shelfCount: 2,
      doorCount: 2,
      doorStyle: 'flat',
      handleStyle: 'knob',
      kickHeight: 0,
      carcassMaterial: 'melamine-16',
      backPanelMaterial: 'hdf-3',
      edgeBanding: 'all-visible',
    },
  ),
  tpl(
    'tall-pantry',
    'Tall Pantry',
    'ארון מזווה גבוה',
    '600×2100×560 mm floor-to-ceiling pantry with 4 shelves',
    'מזווה 600×2100×560 מ"מ, 4 מדפים, גובה תקרה',
    'IconCabinet',
    {
      furnitureType: 'cabinet',
      width: 600,
      height: 2100,
      depth: 560,
      shelfCount: 4,
      doorCount: 2,
      doorStyle: 'flat',
      handleStyle: 'bar',
      kickHeight: 100,
      carcassMaterial: 'melamine-18',
      backPanelMaterial: 'hdf-3',
      edgeBanding: 'all-visible',
    },
  ),
  tpl(
    'wardrobe',
    'Standard Wardrobe',
    'ארון בגדים',
    '1200×2200×600 mm double-door wardrobe',
    'ארון בגדים 1200×2200×600 מ"מ, 2 דלתות',
    'IconWardrobe',
    {
      furnitureType: 'wardrobe',
      width: 1200,
      height: 2200,
      depth: 600,
      shelfCount: 3,
      doorCount: 2,
      doorStyle: 'flat',
      handleStyle: 'bar',
      kickHeight: 0,
      carcassMaterial: 'melamine-18',
      backPanelMaterial: 'hdf-3',
      edgeBanding: 'doors-only',
    },
  ),
  tpl(
    'wardrobe-sliding',
    'Wardrobe Sliding Doors',
    'ארון הזזה',
    '2400×2400×600 mm wide wardrobe for sliding doors',
    'ארון הזזה 2400×2400×600 מ"מ, 6 מדפים',
    'IconWardrobe',
    {
      furnitureType: 'wardrobe',
      width: 2400,
      height: 2400,
      depth: 600,
      shelfCount: 6,
      doorStyle: 'none',
      doorCount: 2,
      handleStyle: 'none',
      kickHeight: 0,
      carcassMaterial: 'melamine-18',
      backPanelMaterial: 'hdf-3',
      edgeBanding: 'none',
    },
  ),
  tpl(
    'bookshelf',
    'Bookcase',
    'כוננית ספרים',
    '800×2000×300 mm deep bookcase with 5 adjustable shelves',
    'כוננית 800×2000×300 מ"מ, 5 מדפים מתכווננים',
    'IconBookshelf',
    {
      furnitureType: 'bookshelf',
      width: 800,
      height: 2000,
      depth: 300,
      shelfCount: 5,
      doorStyle: 'none',
      doorCount: 1,
      handleStyle: 'none',
      kickHeight: 0,
      carcassMaterial: 'plywood-18',
      backPanelMaterial: 'hdf-3',
      edgeBanding: 'all-visible',
    },
  ),
  tpl(
    'desk',
    'Writing Desk',
    'שולחן כתיבה',
    '1400×750×700 mm desk with 2 drawers',
    'שולחן כתיבה 1400×750×700 מ"מ, 2 מגירות',
    'IconDocument',
    {
      furnitureType: 'desk',
      width: 1400,
      height: 750,
      depth: 700,
      shelfCount: 0,
      doorStyle: 'none',
      doorCount: 1,
      drawerCount: 2,
      drawerHeights: [180, 200],
      handleStyle: 'bar',
      kickHeight: 0,
      carcassMaterial: 'plywood-18',
      backPanelMaterial: 'hdf-3',
      edgeBanding: 'all-visible',
    },
  ),
  tpl(
    'bathroom-vanity',
    'Bathroom Vanity',
    'ארון אמבטיה',
    '800×820×450 mm vanity unit with 2 drawers and soft-close',
    'ארון כיור 800×820×450 מ"מ, 2 מגירות סגירה רכה',
    'IconBathroom',
    {
      furnitureType: 'cabinet',
      width: 800,
      height: 820,
      depth: 450,
      shelfCount: 0,
      doorStyle: 'none',
      doorCount: 1,
      drawerCount: 2,
      drawerHeights: [160, 200],
      drawerSlideType: 'soft-close',
      handleStyle: 'knob',
      kickHeight: 80,
      carcassMaterial: 'melamine-16',
      backPanelMaterial: 'hdf-3',
      edgeBanding: 'all-visible',
    },
  ),
  tpl(
    'tv-unit',
    'TV Media Unit',
    'מזנון טלוויזיה',
    '1800×500×400 mm low TV unit with glass doors',
    'מזנון TV נמוך 1800×500×400 מ"מ, דלתות זכוכית',
    'IconTV',
    {
      furnitureType: 'cabinet',
      width: 1800,
      height: 500,
      depth: 400,
      shelfCount: 1,
      doorCount: 2,
      doorStyle: 'glass',
      handleStyle: 'cup',
      kickHeight: 0,
      carcassMaterial: 'melamine-16',
      backPanelMaterial: 'hdf-3',
      edgeBanding: 'all-visible',
    },
  ),
  tpl(
    'bedside',
    'Bedside Table',
    'שידת לילה',
    '450×600×400 mm compact bedside unit with 2 drawers',
    'שידת לילה קומפקטית 450×600×400 מ"מ, 2 מגירות',
    'IconBedside',
    {
      furnitureType: 'cabinet',
      width: 450,
      height: 600,
      depth: 400,
      shelfCount: 0,
      doorStyle: 'none',
      doorCount: 1,
      drawerCount: 2,
      drawerHeights: [150, 180],
      handleStyle: 'knob',
      kickHeight: 0,
      carcassMaterial: 'plywood-17',
      backPanelMaterial: 'hdf-3',
      edgeBanding: 'all-visible',
    },
  ),
  tpl(
    'shaker-kitchen-base',
    'Shaker Kitchen Base',
    'ארון מטבח שייקר',
    '600×900×580 mm shaker-style base unit with full-extension drawers',
    'ארון מטבח סגנון שייקר 600×900×580 מ"מ, מגירות הוצאה מלאה',
    'IconKitchen',
    {
      furnitureType: 'cabinet',
      width: 600,
      height: 900,
      depth: 580,
      shelfCount: 0,
      doorCount: 2,
      doorStyle: 'shaker',
      drawerCount: 3,
      drawerHeights: [160, 180, 200],
      drawerSlideType: 'full-extension',
      handleStyle: 'bar',
      kickHeight: 100,
      carcassMaterial: 'plywood-18',
      backPanelMaterial: 'hdf-3',
      edgeBanding: 'all-visible',
    },
  ),
  tpl(
    'open-display',
    'Open Display Shelving',
    'מדפים פתוחים',
    '1200×2000×280 mm open wall shelving unit, no back',
    'יחידת מדפים פתוחה 1200×2000×280 מ"מ, ללא גב',
    'IconBookshelf',
    {
      furnitureType: 'bookshelf',
      width: 1200,
      height: 2000,
      depth: 280,
      shelfCount: 6,
      doorStyle: 'none',
      doorCount: 1,
      handleStyle: 'none',
      kickHeight: 0,
      hasBack: false,
      carcassMaterial: 'plywood-18',
      backPanelMaterial: 'hdf-3',
      edgeBanding: 'all-visible',
    },
  ),
  // ── Sprint 176 additions ───────────────────────────────────────────────────
  tpl(
    'wine-rack',
    'Wine Rack',
    'מתלה יין',
    '600×900×300 mm wall-mounted wine rack with 3 open display shelves',
    'מתלה יין קיר 600×900×300 מ"מ, 3 מדפי תצוגה פתוחים',
    'IconBookshelf',
    {
      furnitureType: 'bookshelf',
      width: 600,
      height: 900,
      depth: 300,
      shelfCount: 3,
      doorStyle: 'none',
      doorCount: 1,
      handleStyle: 'none',
      kickHeight: 0,
      hasBack: false,
      carcassMaterial: 'plywood-18',
      backPanelMaterial: 'hdf-3',
      edgeBanding: 'all-visible',
    },
  ),
  tpl(
    'corner-cabinet-blind',
    'Corner Cabinet (Blind)',
    'ארון פינה (עיוור)',
    '900×850×600 mm blind corner base cabinet with single door',
    'ארון פינה עיוור 900×850×600 מ"מ, דלת אחת, בסיס',
    'IconCabinet',
    {
      furnitureType: 'cabinet',
      width: 900,
      height: 850,
      depth: 600,
      shelfCount: 1,
      doorCount: 1,
      doorStyle: 'flat',
      handleStyle: 'bar',
      kickHeight: 100,
      carcassMaterial: 'melamine-18',
      backPanelMaterial: 'hdf-3',
      edgeBanding: 'all-visible',
    },
  ),
  tpl(
    'bathroom-vanity-wall',
    'Bathroom Vanity Wall Unit',
    'ארון אמבטיה עליון',
    '600×700×200 mm wall-mounted bathroom cabinet with 1 door and shelf',
    'ארון אמבטיה עליון 600×700×200 מ"מ, דלת אחת, מדף',
    'IconBathroom',
    {
      furnitureType: 'cabinet',
      width: 600,
      height: 700,
      depth: 200,
      shelfCount: 2,
      doorCount: 1,
      doorStyle: 'flat',
      handleStyle: 'knob',
      kickHeight: 0,
      carcassMaterial: 'melamine-16',
      backPanelMaterial: 'hdf-3',
      edgeBanding: 'all-visible',
    },
  ),
];

export function getTemplate(id: string): CabinetTemplate | undefined {
  return TEMPLATES.find((t) => t.id === id);
}

/**
 * Returns sensible default dimensions and settings for each furniture type.
 * Use when the user switches furniture type in the configurator so the config
 * reflects realistic starting values for the selected type.
 */
export function getTemplateDefaults(type: FurnitureType): Partial<CabinetConfig> {
  switch (type) {
    case 'bookshelf':
      return { ...BOOKSHELF_DEFAULTS };
    case 'desk':
      return { ...DESK_DEFAULTS };
    case 'wardrobe':
      return { ...WARDROBE_DEFAULTS };
    case 'panel':
      return { ...PANEL_DEFAULTS };
    case 'cabinet':
    default:
      return { ...CABINET_DEFAULTS };
  }
}
