/**
 * Phase 11 — Typed worker RPC utility (v3.59.3)
 *
 * Wraps a Web Worker postMessage/message-event round-trip in a Promise.
 * Each call gets a unique request ID generated by `nextRpcId()`.
 * The internal event listener removes itself once the matching reply
 * arrives — no memory leaks, no module-level onmessage handler needed.
 *
 * "Latest-wins" stale-drop logic moves to the call sites: the caller
 * stores the return value of `nextRpcId()` and compares it against the
 * module-level counter after the Promise resolves.  If a newer request
 * was dispatched in the meantime the stale result is discarded.
 */

let _nextId = 0;

/** Generate the next unique request ID string. */
export function nextRpcId(): string {
  return String(++_nextId);
}

/**
 * Post `payload` (augmented with `requestId`) to `worker` and await the
 * first MessageEvent whose `data.requestId` matches.
 *
 * Rejects when the worker replies with `type === 'error'`.
 *
 * @typeParam I  Worker input message type (must include `requestId: string`).
 * @typeParam O  Worker output message type (must include `requestId: string`
 *              and `type: string`).
 */
export function workerCall<I extends { requestId: string }, O extends { requestId: string; type: string }>(
  worker: Worker,
  payload: Omit<I, 'requestId'>,
  requestId: string,
): Promise<O> {
  return new Promise<O>((resolve, reject) => {
    const handler = (event: MessageEvent<O>) => {
      if (event.data.requestId !== requestId) return;
      worker.removeEventListener('message', handler);
      if (event.data.type === 'error') {
        const msg = (event.data as Record<string, unknown>)['errorMessage'] ?? 'Worker error';
        reject(new Error(String(msg)));
      } else {
        resolve(event.data);
      }
    };
    worker.addEventListener('message', handler);
    worker.postMessage({ ...payload, requestId } as I);
  });
}
