export const CALCULATOR_CATALOG = [
  { id: 'finish', titleKey: 'finish.title' },
  { id: 'face-frame', titleKey: 'faceFrame.title' },
  { id: 'cabinet-door', titleKey: 'cabinetDoor.title' },
  { id: 'drawer-box', titleKey: 'drawerBox.title' },
  { id: 'screw-pullout', titleKey: 'screwPullout.title' },
  { id: 'kerf-bending', titleKey: 'kerfBending.title' },
  { id: 'dado-rabbet', titleKey: 'dadoRabbet.title' },
  { id: 'finishing-coat', titleKey: 'finishingCoat.title' },
  { id: 'wood-turning', titleKey: 'woodTurning.title' },
  { id: 'frame-panel', titleKey: 'framePanel.title' },
  { id: 'taper-jig', titleKey: 'taperJig.title' },
  { id: 'stair-stringer', titleKey: 'stairStringer.title' },
  { id: 'box-joint', titleKey: 'boxJoint.title' },
  { id: 'glue-coverage', titleKey: 'glueCoverage.title' },
  { id: 'planer-passes', titleKey: 'planerPasses.title' },
  { id: 'honing-guide', titleKey: 'honingGuide.title' },
  { id: 'crown-moulding', titleKey: 'crownMoulding.title' },
  { id: 'router-circle', titleKey: 'routerCircle.title' },
  { id: 'cove-cut', titleKey: 'coveCut.title' },
  { id: 'moisture-shrinkage', titleKey: 'moistureShrinkage.title' },
  { id: 'rafter-length', titleKey: 'rafterLength.title' },
  { id: 'router-template', titleKey: 'routerTemplate.title' },
  { id: 'half-lap', titleKey: 'halfLap.title' },
  { id: 'spline-joint', titleKey: 'splineJoint.title' },
  { id: 'shelf-deflection', titleKey: 'shelfDeflection.title' },
  { id: 'pocket-hole', titleKey: 'pocketHole.title' },
  { id: 'dowel-joint', titleKey: 'dowelJoint.title' },
  { id: 'mortise-tenon', titleKey: 'mortiseTenon.title' },
  { id: 'dovetail-layout', titleKey: 'dovetailLayout.title' },
] as const;

export type CalculatorId = (typeof CALCULATOR_CATALOG)[number]['id'];
